--instance Eq a => Eq (Maybe a) where
--  Just x  == Just y  = x == y
--  Nothing == Nothing = True
--  _       == _       = False
--instance Eq a => Eq [a] where
--  []     == []     = True
--  (x:xs) == (y:ys) = (x == y) && (xs == ys)
--  _      == _      = False
